spring:
  application:
    name: eum
  profiles:
    active: ${SPRING_PROFILE:dev}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${LOG_LEVEL:DEBUG}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000      # 30분
  refresh-expiration: 1209600000  # 14일

kakao:
  mobility:
    api-key: ${KAKAO_MOBILITY_API_KEY:}